ROW_GRID = 25
COL_GRID = 50
EMPTY = "EMPTY"

HEIGHT_SOLDIER = 6
HEIGHT_BODY_SOLDIER = 4
HEIGHT_LEGS_SOLDIER = 2
WIDTH_SOLDIER = 2
BODY_SOLDIER = "BODY_SOLDIER"
LEG_SOLDIER = "LEG_SOLDIER"

HEIGHT_FLAG = 3
WIDTH_FLAG = 4
FLAG = "FLAG"