ROW_GRID = 25
COL_GRID = 50
EMPTY = "EMPTY"

P_SCREEN_WIDTH = 1200
P_SCREEN_HEIGHT = 600

SIZE_SQUARE = 24

P_GRASS_AMOUNT = 20
P_GRASS_WIDTH = 4 * SIZE_SQUARE
P_GRASS_HEIGHT = 4 * SIZE_SQUARE

P_FLAG_WIDTH = 80
P_FLAG_HEIGHT = 80

HEIGHT_SOLDIER = 6
HEIGHT_BODY_SOLDIER = 4
HEIGHT_LEGS_SOLDIER = 2
WIDTH_SOLDIER = 2
BODY_SOLDIER = "BODY_SOLDIER"
LEG_SOLDIER = "LEG_SOLDIER"
P_SOLIDER_WIDTH = 50
P_SOLIDER_HEIGHT = 50

HEIGHT_FLAG = 3
WIDTH_FLAG = 4
FLAG = "FLAG"

SUM_MINES = 20
HEIGHT_MINE = 1
WIDTH_MINE = 3
MINE = "MINE"