# Matrix grid
ROW_GRID = 25
COL_GRID = 50
EMPTY = "EMPTY"

# Screen
P_SCREEN_WIDTH = 1200
P_SCREEN_HEIGHT = 600

# Square
SIZE_SQUARE = 24

# Grass
P_GRASS_AMOUNT = 20
P_GRASS_WIDTH = 2 * SIZE_SQUARE
P_GRASS_HEIGHT = 2* SIZE_SQUARE

# Flag
FLAG_HEIGHT = 3
FLAG_WIDTH = 4
P_FLAG_HEIGHT = FLAG_HEIGHT * SIZE_SQUARE
P_FLAG_WIDTH = FLAG_WIDTH * SIZE_SQUARE
FLAG = "FLAG"

# Soldier
SOLDIER_HEIGHT = 6
BODY_SOLDIER_HEIGHT = 4
LEGS_SOLDIER_HEIGHT = 2
SOLDIER_WIDTH = 2
P_SOLIDER_WIDTH = SOLDIER_WIDTH * SIZE_SQUARE
P_SOLIDER_HEIGHT = BODY_SOLDIER_HEIGHT * SIZE_SQUARE
SOLDIER_BODY = "BODY_SOLDIER"
SOLDIER_LEG = "LEG_SOLDIER"

# Mines
SUM_MINES = 20
MINE_HEIGHT = 1
MINE_WIDTH = 3
MINE = "MINE"